config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show] 
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id

end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
def tag_list
    tags.map(&:tagu).join(', ')
  end

  # タグを保存する際に重複を削除する(変更箇所)
  def tag_list=(tags)
    unique_tags = tags.split(',').map(&:strip).uniq
    self.tags = unique_tags.map { |tag_name| Tag.find_or_create_by(tagu: tag_name) }
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

mount_uploader :image, ImageUploader
mount_uploader :image2, ImageUploader
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @tweets = Tweet.all
        #Tweetテーブルの中にある情報を全部持ってきてね
    
        if params[:search] != nil && params[:search] != ''
            #キーワード検索する  
              search_keyword = params[:search].split(/[[:blank:]]+/)  
              search_keyword.each do |keyword|
                next if keyword == ""
                    @tweets = @tweets.where("shop LIKE ? OR place LIKE ? OR menu LIKE ? OR detail LIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%")
              end
        end
        if params[:tag_ids].present?
            tweet_ids = []
            params[:tag_ids].each do |key, value| 
              if value == "1"
                tag_tweets = Tag.find_by(name: key).tweets
                @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
                puts key
              end
            end
            tweet_ids = tweet_ids.uniq
            @tweets = @tweets.where(id: tweet_ids) if tweet_ids.present?
        end
        if params[:tag]
      Tag.create(name: params[:tag])
    end

end


  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      Tag.create(name: params[:tag]) if params[:tag].present?
      redirect_to action: :index
    else
      redirect_to action: :new
    end
  end

  def show
    @tweet = Tweet.find_by(id: params[:id])
    redirect_to tweets_path, alert: "Tweetが見つかりませんでした" if @tweet.nil?
  
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to action: :show, id: tweet.id
    else
      redirect_to action: :new
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private

  def tweet_params
    params.require(:tweet).permit(:shop, :place, :menu, :detail, :image, :price,:image2, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
    @tweets = @user.tweets
    @likes = @user.liked_tweets

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

 <head>

 <title>Cafe</title>

 <meta name="viewport" content="width=device-width,initial-scale=1">

<%= csrf_meta_tags %>

 <%= csp_meta_tag %>



 <script src="https://kit.fontawesome.com/7683da1876.js" crossorigin="anonymous"></script>

 <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

 <%= javascript_importmap_tags %>
 
  </head>

<body>

<header>

 <h1>Cafe</h1>

 <div class="header-list">

<ul>
 <% if user_signed_in? %>

<li><%= button_to 'logout', destroy_user_session_path, method: :delete, class: "logout" %></li>

 <% else %>

<li><%= link_to "sign up", new_user_registration_path %></li>

<li><%= link_to "login", new_user_session_path %></li>

 <% end %>

</ul>
 </div>

</header>

<main>

 <%= yield %>
</main>

</body>





</html>

app/views/tweets/edit.html.erb
<%# indexページと背景色を合わせるために全体を囲む %>
<div class="body">

  <%# フォーム全体をカードデザインにするためのコンテナ %>
  <div class="form-container">

    <h1>Cafe</h1>
    <h3>Edit</h3>

    <%= form_for @tweet do |f| %>

      <%# 各入力項目をこのdivで囲む %>
      <div class="form-field">
        <%= f.label :shop, "shop" %>
        <%= f.text_field :shop %>
      </div>

      <div class="form-field">
        <%= f.label :place, "place" %>
        <%= f.text_field :place %>
      </div>

      <div class="form-field">
        <%= f.label :price, "price" %>
        <%= f.text_field :menu %>
      </div>

      <div class="form-field">
        <%= f.label :detail, "detail" %>
        <%= f.text_area :detail %>
      </div>

      <div class="form-field">
        <%= f.label :image, "image" %>
        <%= f.file_field :image %>
      </div>

      <div class="form-field">
        <%= f.label :image2, "image2" %>
        <%= f.file_field :image2 %>
      </div>

      <%# タグ選択エリア %>
      <div class="form-field">
        <p class="tag-label">タグを選択</p>
        <div class="tagu">
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class="tagu1">
              <%= tag.label do %>
                <%= tag.check_box %>
                <span><%= tag.text %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <%# ボタンを配置するエリア %>
      <div class="form-actions">
        <%= f.submit "更新する", class: "form-submit-button" %>
      </div>

    <% end %>

    <div class="form-actions">
      <%# 「一覧に戻る」ボタンの代わりに詳細ページへのリンクを配置 %>
      <%= link_to "戻る", tweet_path(@tweet), class: "form-submit-button" %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="body">
   <%= link_to new_tweet_path, class: "custom-button-v3" do %>
   <span>New post</span>
   <% end %>

    <% if user_signed_in? %>
      <%= link_to user_path(current_user.id), class: "custom-button-v3" do %>
         <span>My page</span>
      <% end %>
   <% end %>

   <div class="search-container">
      <form action="" class="search-box">
         <input type="text" class="search-input" name="search" id="search-input">
         <button type="submit" class="search-btn" aria-label="検索"></button>
      </form>
   </div>

      <div class="tagu">
            <% Tag.all.each do |t| %>
               <div class="tagu1">
                     <label><%= check_box :tag_ids, t.name %><span><%= t.name %></span></label>
               </div>
            <% end %>
            <div class="tagutuika">
               <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
                  <%= text_field_tag :tag %>
                  <%= submit_tag 'タグを追加' %>
               <% end %>

            </div>
      </div>



   <div class="tweets-container">

   <div class="toukou" style="--slide-count: <%= @tweets.count %>;">
      
      <% @tweets.each do |t| %>
         <div class="tweet">
         
         <div class="gazou">
               <%= link_to tweet_path(t.id), class: "slide-photo" do %>
                  <%= image_tag t.image_url, size: "400x400" if t.image? %>
               <% end %>
         </div>
         <%= t.shop %>
         <%= t.place %>
         
         <% if user_signed_in? %>
         
               <% if current_user.already_liked?(t) %>
               <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                  <%# ↓ この行のclassに「liked-heart」を追加 %>
                  <i class="fas fa-heart liked-heart"></i><%= t.likes.count %>
               <% end %>
               <% else %>
               <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
               <i class="far fa-heart"></i><%= t.likes.count %>
               <% end %>
            <% end %>
         <% else %>
            <i class="far fa-heart"></i><%= t.likes.count %>
         <% end %>

         
         </div>
      <% end %>

      <% @tweets.each do |t| %>
         <div class="tweet">
         
            <div class="gazou">
               <%= link_to tweet_path(t.id), class: "slide-photo" do %>
                  <%= image_tag t.image_url, size: "400x400" if t.image? %>
               <% end %>
            </div>
         <%= t.shop %>
         <%= t.place %>
         
         <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
               <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
               <i class="fas fa-heart"></i><%= t.likes.count %>
               <% end %>
            <% else %>
               <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
               <i class="far fa-heart"></i><%= t.likes.count %>
               <% end %>
            <% end %>
         <% else %>
            <i class="far fa-heart"></i><%= t.likes.count %>
         <% end %>

         
         </div>
      <% end %>

   </div>
   </div>
</div>
   

app/views/tweets/new.html.erb
<%# indexページと背景色を合わせるために全体を囲む %>
<div class="body">

  <%# フォーム全体をカードデザインにするためのコンテナ %>
  <div class="form-container">
  

    <h1>Cafe</h1>
    <h3>New Post</h3>

    <%= form_for @tweet do |f| %>

      <%# 各入力項目をこのdivで囲む %>
      <div class="form-field">
        <%= f.label :shop, "shop" %>
        <%= f.text_field :shop, placeholder: "" %>
      </div>

      <div class="form-field">
        <%= f.label :place, "place" %>
        <%= f.text_field :place, placeholder: "" %>
      </div>

      <div class="form-field">
        <%= f.label :price, "price" %>
        <%= f.text_field :menu, placeholder: "" %>
      </div>

      <div class="form-field">
        <%= f.label :detail, "detail" %>
        <%= f.text_area :detail, placeholder: "" %>
      </div>

      <div class="form-field">
        <%= f.label :image, "image" %>
        <%= f.file_field :image %>
      </div>

      <div class="form-field">
        <%= f.label :image2, "image2" %>
        <%= f.file_field :image2 %>
      </div>

      <%# タグ選択エリア %>
      <div class="form-field">
        <p class="tag-label">タグを選択</p>
        <div class="tagu">
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class="tagu1">
              <%= tag.label do %>
                <%= tag.check_box %>
                <span><%= tag.text %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>



      <%# ボタンを配置するエリア %>
      <div class="form-actions">
        <%= f.submit "投稿する", class: "form-submit-button" %>
      </div>

    <% end %>

    <div class="form-actions">
      <%= link_to "Top", tweets_path, class: "custom-button-v3" %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="body">
  <div class="page-container">

    <%# --- ページタイトル --- %>
    <div class="title">
      <h1>Cafe</h1>
      <h3></h3>
    </div>

    <%# --- メインコンテンツカード --- %>
    <div class="tweet-show-card">
      
      <%# --- 左カラム (画像ギャラリー) --- %>
      <div class="tweet-gallery">
        <% if @tweet.image? %>
          <%= image_tag @tweet.image_url, class: "main-image" %>
        <% end %>
        <% if @tweet.image2? %>
          <%= image_tag @tweet.image2_url, class: "sub-image" %>
        <% end %>
      </div>

      <%# --- 右カラム (詳細情報) --- %>
      <div class="tweet-details">
        <h2 class="tweet-shop-name"><%= @tweet.shop %></h2>
        
        <div class="tweet-info-group">
          <p class="tweet-info-item"><strong>place:</strong> <%= @tweet.place %></p>
          <p class="tweet-info-item"><strong>price:</strong> <%= @tweet.menu %></p>
          <p class="tweet-info-item"><strong></strong> <%= @tweet.created_at.strftime("%Y年%m月%d日") %></p>
        </div>
        
        <div class="tweet-detail-text">
          <p><%= simple_format(@tweet.detail) %></p>
        </div>

        <%# --- タグ --- %>
        <div class="tweet-tags">
          <% @tweet.tags.each do |tag| %>
            <span class="tag-item"><%= tag.name %></span>
          <% end %>
        </div>

        <%# --- アクションボタン (いいね・編集・削除) --- %>
        <div class="tweet-actions">
          <div class="like-button">
            <% if user_signed_in? %>
              <% if current_user.already_liked?(@tweet) %>
                <%= link_to tweet_like_path(@tweet), method: :delete do %>
                  <i class="fa-solid fa-heart"></i><span><%= @tweet.likes.count %></span>
                <% end %>
              <% else %>
                <%= link_to tweet_likes_path(@tweet), method: :post do %>
                  <i class="fa-regular fa-heart"></i><span><%= @tweet.likes.count %></span>
                <% end %>
              <% end %>
            <% else %>
              <i class="fa-regular fa-heart"></i><span><%= @tweet.likes.count %></span>
            <% end %>
          </div>
          <div class="edit-delete-links">
            <%= link_to "edit", edit_tweet_path(@tweet.id) %>
            <%= button_to "delete", tweet_path(@tweet), method: :delete, class: "button-delete" %>
          </div>
        </div>
      </div>
    </div>

    
    <%# --- ページ下部リンク --- %>
    <div class="page-footer">
      <%= link_to tweets_path, class: "custom-button-v3" do %>
        <span>Top</span>
      <% end %>
    </div>

  </div>
</div>

<script>
  // turbo:load イベントは、初回読み込み時とTurboによる画面遷移時の両方で発火します
  document.addEventListener('turbo:load', function() {

    // それぞれの画像要素を取得
    const mainImage = document.querySelector('.main-image');
    const subImage = document.querySelector('.sub-image');

    // 両方の画像が存在する場合のみ、処理を実行
    if (mainImage && subImage) {

      // メイン画像をクリックしたときの処理
      mainImage.addEventListener('click', function() {
        mainImage.style.display = 'none'; // メイン画像を非表示に
        subImage.style.display = 'block'; // サブ画像を表示
      });

      // サブ画像をクリックしたときの処理
      subImage.addEventListener('click', function() {
        subImage.style.display = 'none'; // サブ画像を非表示に
        mainImage.style.display = 'block'; // メイン画像を表示
      });
    }
  });
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="body">
  <div class="page-container">

    <%# --- ページタイトル --- %>
    <div class="title">
      <h1>My Page</h1>
    </div>

    <%# --- プロフィールセクション --- %>
    <div class="profile-card">
      <p><strong>name:</strong> <%= @user.name %></p>
      <p><strong>mail:</strong> <%= @user.email %></p>
      <p><strong>profile:</strong><br>
        <%= simple_format(@user.profile) %></p>

      <% if current_user.id == @user.id %>
        <%= link_to "edit", edit_user_registration_path, class: "button-primary" %>
      <% end %>
    </div>

    <%# --- 投稿一覧セクション --- %>
    <h2 class="section-title">投稿</h2>
    <div class="posts-grid">
      <% @user.tweets.each do |t| %>
        <div class="post-card">
          <% if t.image? %>
            <%= image_tag t.image_url, class: "post-card-image" %>
          <% end %>
          <div class="post-card-content">
            <p class="post-card-shop"><%= t.shop %></p>
            <p class="post-card-place"><%= t.place %></p>
            <p class="post-card-menu"><%= t.menu %></p>
            <p class="post-card-detail"><%= t.detail %></p>
          </div>
          <div class="post-card-actions">
            <%= link_to "edit", edit_tweet_path(t.id) %>
            <%= button_to "delete", tweet_path(t.id), method: :delete, class: "button-delete" %>
          </div>
        </div>
      <% end %>
    </div>

    <%# --- いいね一覧セクション --- %>
    <h2 class="section-title">いいねした投稿</h2>
    <div class="posts-grid">
      <% @likes.each do |like| %>
        <div class="post-card">
          <% if like.image? %>
            <%= image_tag like.image_url, class: "post-card-image" %>
          <% end %>
          <div class="post-card-content">
            <p class="post-card-shop"><%= like.shop %></p>
            <p class="post-card-place"><%= like.place %></p>
            <%# いいねのハートアイコンなどをここに追加できます %>
          </div>
        </div>
      <% end %>
    </div>

    <%# --- ページ下部リンク --- %>
    <div class="page-footer">
      <%= link_to tweets_path, class: "custom-button-v3" do %>
        <span>Top</span>
      <% end %>
    </div>

  </div>
</div>